### ISSUE TITLE
Error when running with rows greater than 9999

### ISSUE THREAD

**Issue by arjay55** [AutoViML/featurewiz#10]
I am running into an error when the rows of the dataframe to be feature reduced is greater than 9999. The stack trace is shown below:

>>> outputs = featurewiz(dataset.iloc[:10500,:], collist, corr_limit=0.93, verbose=1, dask_xgboost_flag=False)

Skipping feature engineering since no feature_engg input...
Skipping category encoding since no category encoders specified in input...
Loading train data...
    Shape of your Data Set loaded: (10500, 2880)
Loading test data...
    No file given. Continuing...
Classifying features using 10000 rows...
    loading a random sample of 10000 rows into pandas for EDA

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_17760/2016861536.py in <module>
----> 1 outputs = featurewiz(dataset.iloc[:10500,:], collist, corr_limit=0.93, verbose=1, dask_xgboost_flag=False)

~/miniconda3/envs/CS280/lib/python3.7/site-packages/featurewiz/featurewiz.py in featurewiz(dataname, target, corr_limit, verbose, sep, header, test_data, feature_engg, category_encoders, dask_xgboost_flag, nrows, **kwargs)
   1082             targets = copy.deepcopy(target)
   1083         ##### you can use
-> 1084         train_small = select_rows_from_dataframe(dataname, targets, nrows_limit, DS_LEN=dataname.shape[0])
   1085         features_dict = classify_features(train_small, target)
   1086     else:

~/miniconda3/envs/CS280/lib/python3.7/site-packages/featurewiz/featurewiz.py in select_rows_from_dataframe(train_dataframe, targets, nrows_limit, DS_LEN)
   3986             list_of_few_classes = train_dataframe[each_target].value_counts()[train_dataframe[each_target].value_counts()<=10].index.tolist()
   3987             train_small = train_dataframe.loc[~(train_dataframe[each_target].isin(list_of_few_classes))]
-> 3988         train_small, _ = train_test_split(train_dataframe, test_size=test_size, stratify=train_dataframe[targets])
   3989     else:
   3990         ### For Regression problems: load a small sample of data into a pandas dataframe ##

~/miniconda3/envs/CS280/lib/python3.7/site-packages/sklearn/model_selection/_split.py in train_test_split(test_size, train_size, random_state, shuffle, stratify, *arrays)
   2439         cv = CVClass(test_size=n_test, train_size=n_train, random_state=random_state)
   2440 
-> 2441         train, test = next(cv.split(X=arrays[0], y=stratify))
   2442 
   2443     return list(

~/miniconda3/envs/CS280/lib/python3.7/site-packages/sklearn/model_selection/_split.py in split(self, X, y, groups)
   1598         """
   1599         X, y, groups = indexable(X, y, groups)
-> 1600         for train, test in self._iter_indices(X, y, groups):
   1601             yield train, test
   1602 

~/miniconda3/envs/CS280/lib/python3.7/site-packages/sklearn/model_selection/_split.py in _iter_indices(self, X, y, groups)
   1939         if np.min(class_counts) < 2:
   1940             raise ValueError(
-> 1941                 "The least populated class in y has only 1"
   1942                 " member, which is too few. The minimum"
   1943                 " number of groups for any class cannot"

ValueError: The least populated class in y has only 1 member, which is too few. The minimum number of groups for any class cannot be less than 2.

I have tried replicating it over a dataframe with random numbers only and the same happened.

**Comment by AutoViML** [comment]
HI @arjay55 👍 
This problem has been fixed. Please upgrade via:
```pip install featurewiz --upgrade ```

Then let us know if it works.
AutoViML team

**Comment by arjay55** [comment]
Hi. I'm still encountering an error. 

Skipping feature engineering since no feature_engg input...
Skipping category encoding since no category encoders specified in input...
Loading train data...
    Shape of your Data Set loaded: (143974, 2880)
Loading test data...
    No file given. Continuing...
Classifying features using 10000 rows...
    loading a random sample of 10000 rows into pandas for EDA

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_328/641257510.py in <module>
----> 1 outputs = featurewiz(dataset, collist, corr_limit=0.93, verbose=1, dask_xgboost_flag=False)

~/miniconda3/envs/CS280/lib/python3.7/site-packages/featurewiz/featurewiz.py in featurewiz(dataname, target, corr_limit, verbose, sep, header, test_data, feature_engg, category_encoders, dask_xgboost_flag, nrows, **kwargs)
   1082             targets = copy.deepcopy(target)
   1083         ##### you can use
-> 1084         train_small = select_rows_from_dataframe(dataname, targets, nrows_limit, DS_LEN=dataname.shape[0])
   1085         features_dict = classify_features(train_small, target)
   1086     else:

~/miniconda3/envs/CS280/lib/python3.7/site-packages/featurewiz/featurewiz.py in select_rows_from_dataframe(train_dataframe, targets, nrows_limit, DS_LEN)
   4001             list_of_few_classes = train_dataframe[each_target].value_counts()[train_dataframe[each_target].value_counts()<=3].index.tolist()
   4002             train_dataframe = train_dataframe.loc[~(train_dataframe[each_target].isin(list_of_few_classes))]
-> 4003         train_small, _ = train_test_split(train_dataframe, test_size=test_size, stratify=train_dataframe[targets])
   4004     else:
   4005         ### For Regression problems: load a small sample of data into a pandas dataframe ##

~/miniconda3/envs/CS280/lib/python3.7/site-packages/sklearn/model_selection/_split.py in train_test_split(*arrays, **options)
   2129     n_samples = _num_samples(arrays[0])
   2130     n_train, n_test = _validate_shuffle_split(n_samples, test_size, train_size,
-> 2131                                               default_test_size=0.25)
   2132 
   2133     if shuffle is False:

~/miniconda3/envs/CS280/lib/python3.7/site-packages/sklearn/model_selection/_split.py in _validate_shuffle_split(n_samples, test_size, train_size, default_test_size)
   1812             'resulting train set will be empty. Adjust any of the '
   1813             'aforementioned parameters.'.format(n_samples, test_size,
-> 1814                                                 train_size)
   1815         )
   1816 

ValueError: With n_samples=0, test_size=0.9 and train_size=None, the resulting train set will be empty. Adjust any of the aforementioned parameters.

**Comment by AutoViML** [comment]
Hi @arjay55 👍 
Sorry I cannot tell where this error is coming from without the data. I also noticed that you have not provided the version number of featurewiz you are using. Please note that the latest version is 0.0.61 and you need to show me you have upgraded to this version and if you can attach a small sample dataset (via zip file) here.
Thanks
AutoViML

**Comment by arjay55** [comment]
Hi. Already my run on my dataset I confirmed that the bug is resolved. Thanks!
